### ISSUE TITLE
User List Page sorts Descending only

### ISSUE THREAD

**Issue by Cookzenberg** [Uintra/Uintra#11]
I can't see how to change the User List Page to sort by ascending Name (or any other field); the default is descending Z - A.

![image](https://user-images.githubusercontent.com/29954530/49437623-e8b23580-f7b3-11e8-8697-6738c9b56719.png)

![image](https://user-images.githubusercontent.com/29954530/49437692-19926a80-f7b4-11e8-95f1-78567c5b4238.png)

Please advise.

Thanks
Andy

**Comment by denprodan** [comment]
Thanks. We will crete internal task and fix this bug in next release

**Comment by Cookzenberg** [comment]
Thanks Denis. Is there somewhere else I can look to see what is on your road map so I'm not creating unnecessary noise here if there is something you are already planning to do? 

e.g. It would be very useful to be able to see the phone number on the directory... but I'm sure you already plan to do this because the help text on the search bar states as much.

**Comment by denprodan** [comment]
Hi Cookzenberg
We'll include issue about users phone number in next releases

**Comment by denprodan** [comment]
Hi again, we have also added link to our future releases here https://uintra.com/release-plan/. So, you can always see up do date information about future releases details and latest released info here https://uintra.com/releases/ 😊

**Comment by Cookzenberg** [comment]
Hi Denis, thanks for the info.

**Comment by denprodan** [comment]
Hi Cookzenberg. 
We've fixed User List Page sort in 1.1.0.0
Version 1.1.0.0 already released
Looking forward for feedback from you

**Comment by Cookzenberg** [comment]
I see an exception when running in debug and a the page is grey and blank in release mode.

Did you change the required version of Elasticsearch by any chance? 

I'm still running 5.2.1.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Uintra.Search
  StackTrace:
   at Uintra.Search.ElasticIndex.GlobalFacets(IReadOnlyDictionary`2 facets, String facetName)
   at Uintra.Search.ElasticIndex.ParseResults(ISearchResponse`1 response)
   at Uintra.Search.ElasticIndex.Search(SearchTextQuery query)
   at Compent.Uintra.Controllers.UserListController.GetActiveUserIds(Int32 skip, Int32 take, String query, Int64& totalHits, String orderBy, Int32 direction) in C:\Users\Andrew.Cook\source\repos\Intranet\Intranet\Controllers\UserListController.cs:line 46
   at Uintra.Users.Web.UserListControllerBase.GetActiveUsers(Int32 skip, Int32 take, String orderBy, Int32 direction, Boolean& isLastRequest, String query)
   at Uintra.Users.Web.UserListControllerBase.Render(UserListModel model)
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

**Comment by denprodan** [comment]
Did you rebuild search index?

пт, 21 дек. 2018 г., 17:57 Cookzenberg notifications@github.com:

**Comment by Cookzenberg** [comment]
Yes... localhost says REBUILD INDEX DONE but the error still occurs.

**Comment by Cookzenberg** [comment]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Uintra.Search
  StackTrace:
   at Uintra.Search.ElasticIndex.GlobalFacets(IReadOnlyDictionary`2 facets, String facetName)
   at Uintra.Search.ElasticIndex.ParseResults(ISearchResponse`1 response)
   at Uintra.Search.ElasticIndex.Search(SearchTextQuery query)
   at Compent.Uintra.Controllers.SearchController.Search(SearchFilterModel model) in SearchController.cs:line 48

**Comment by 1nsolenT** [comment]
Hi @Cookzenberg .
Please, insert this instead of `<elmah></elmah>` in web.config:
`<elmah>
    <security allowRemoteAccess="false" />
    <errorLog type="Elmah.XmlFileErrorLog, Elmah" logPath="~/App_Data/Errors" />
  </elmah>
  <location path="elmah.axd" inheritInChildApplications="false">
    <system.web>
      <httpHandlers>
        <add verb="POST,GET,HEAD" path="elmah.axd" type="Elmah.ErrorLogPageFactory, Elmah" />
      </httpHandlers>
    </system.web>
    <system.webServer>
      <handlers>
        <add name="ELMAH" verb="POST,GET,HEAD" path="elmah.axd" type="Elmah.ErrorLogPageFactory, Elmah" preCondition="integratedMode" />
      </handlers>
    </system.webServer>
  </location>`

and open url like:     [your site domain]/elmah.axd
On this page you need to find out some errors related to elastic search (they will contains an invalid underlying API call to ES server) and put them over here.

Thanks, Max.

**Comment by Cookzenberg** [comment]
![image](https://user-images.githubusercontent.com/29954530/50355670-69f52080-0547-11e9-8779-c60e85e3b1d3.png)

Like this?

**Comment by Cookzenberg** [comment]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"elmah.axd","index_uuid":"_na_","index":"elmah.axd"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"elmah.axd","index_uuid":"_na_","index":"elmah.axd"},"status":404}

**Comment by 1nsolenT** [comment]
Nope :)
 [your site domain]/elmah.axd in Uintra (like http://myIntranet.com/elmah.axd), not in ES server.

**Comment by Cookzenberg** [comment]
It didn't look that useful! Doing it properly now, I hope.

**Comment by Cookzenberg** [comment]
Here is the result from the phone book call:

Invalid NEST response built from a unsuccessful low level call on POST: /uintra_intranet/_search # Audit trail of this API call: - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.3080308 # ServerError: ServerError: 400Type: search_phase_execution_exception Reason: "all shards failed" CausedBy: "Type: query_shard_exception Reason: "No mapping found for [fullName.sort_normalizer] in order to sort on"" # OriginalException: System.Net.WebException: The remote server returned an error: (400) Bad Request. at System.Net.HttpWebRequest.GetResponse() at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) # Request: <Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.> # Response: <Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>

Please note I found out why the general search wasn't working and that is working again now, so just the phone book problem outstanding.

**Comment by 1nsolenT** [comment]
Sorry, maybe i missed something, but what is a "phone book" (uintra does not have any feature like this by default)? Did you override something (or extend), especially if it's related to searchable entities? 
Is this error occurred in user list page or not? Because if you fixed general search, then user list page should work.

**Comment by Cookzenberg** [comment]
Sorry yes it is the user list page. 
I haven't changed anything related to the searchable entities. 
And the general search is no longer working any more either... it doesn't give any results. I'm just checking to see if it throws similar errors or not.

**Comment by Cookzenberg** [comment]
I deleted the page and recreated it and I'm still seeing the same error in the ES logs:

org.elasticsearch.transport.RemoteTransportException: [WPEA8E8][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [fullName.sort_normalizer] in order to sort on
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:262) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:688) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:540) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:516) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:351) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:322) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:319) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:610) [elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) [elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.2.1.jar:5.2.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

I'll post a screenshot of my user page configuration now.

**Comment by Cookzenberg** [comment]
![image](https://user-images.githubusercontent.com/29954530/50373041-9012d300-05d0-11e9-8cef-7d2608fdd259.png)

**Comment by Cookzenberg** [comment]
Hi Max

I deployed uIntra onto an Azure Webapp and Elasticsearch 5.2.1 onto an Azure VM.

In this configuration the user list page works just fine.

I don't see any difference in the Umbraco back office configuration in this new environment that differs from my local machine, or the version I have on a Windows Server box inside my network, neither of which work.

But I'm less worried about finding out why as the Azure hosted version is my preferred solution for a production intranet anyway. 

Unless you had any thoughts about the possible cause of the problem that might benefit future readers, I'll close the ticket.

Andy

PS I had to install the ES Ingest Attachment plugin as a separate step that I didn't have to do on either of my previous installations. I've no idea why.

**Comment by 1nsolenT** [comment]
Hi Andy.

At the beginning, i thought that the reason was in updating uintra from version 0.5 to 1.1, but when i done updating process - user list worked fine. 

Have you tried to install clean uintra (v 1.1) on your local environment with your local ES server? Did you have the same issue, related to "No mapping found for [fullName.sort_normalizer] in order to sort on"?

I was able to reproduce this error only when I manually commented out a piece of code responsible for the field mapping (in our case "fullName"). I assume that this piece of code did not run for some reason (possibly due to attachment plugin.)

Try to add an attachment plugin to your local ES server. I think without this plugin, the index was not built correctly, but for some reason "Rebuild index" did't throw any error.
