### ISSUE TITLE
Mention Controller

### ISSUE THREAD

**Issue by ChrisAngel447** [Uintra/Uintra#3]
Hi guys,

I have found something that I wanted to run by you with a connection to the mention controller. 
After installing and creating Uintra users I tried the new features like mention someone in a Bulletins and saw nothing was happening. After a bit of debugging I came across the mention controller in the API folder and found the below error: 
![image](https://user-images.githubusercontent.com/9823098/48550138-8d8ad280-e8da-11e8-9627-6da3af0ed816.png)

This is in version 0.5 of uintra and 10.7.4 of Umbraco using .net 4.7.1.

I have not changed anything on the code other than logo’s that have been changed and adding upcoming events, Content panel, document Library panel, global panel and latest activities nodes.

Kind regards and thanks

Chris

**Comment by KasperUintra** [comment]
Hi Chris,
The problem is related to elastic search:
The supported Elasticsearch version is 5.2.1 please check if you are using this.

If the version is correct, then you need to rebuild the elasticsearch index manually from the Umbraco control. After the rebuild the problem should be solved!
Here is a screenshot:

![image](https://user-images.githubusercontent.com/39656039/48554655-4521e380-e8df-11e8-953f-a466b250e460.png)

Let me know if this fixed the problem!

**Comment by ChrisAngel447** [comment]
Good morning Denis and Kasper,
Sorry for the late reply, I have tried the above but seems like its still not working.
I rebuilt the search and then refreshed the page and tried as you can see bellow:
![image](https://user-images.githubusercontent.com/9823098/48602379-a0a1af00-e97b-11e8-9a30-1cdb06b830e6.png)
And here my console too if this helps:
![image](https://user-images.githubusercontent.com/9823098/48602418-bca55080-e97b-11e8-976f-51493ade3c27.png)

If there is anything you might need please let me know.

**Comment by denprodan** [comment]
Hi Chris. Thanks for feedback. What version of elasticsearch do you use?

пт, 16 нояб. 2018 г., 8:44 Chris notifications@github.com:

**Comment by denprodan** [comment]
Unfortunately for now we didn't support any versions of elasticsearch
except 5.2.1. Please downgrade your version to 5.2.1 and rebuild index.
Looking forward for feedback

пт, 16 нояб. 2018 г., 10:26 Chris notifications@github.com:

**Comment by ChrisAngel447** [comment]
Hi Denis,
I tried downgrading to 5.2.0 since I dont see a 5.2.1 on NuGet but get the following error:
![image](https://user-images.githubusercontent.com/9823098/48611503-15caaf80-e98f-11e8-9adb-a30844e2fb85.png)
I see that my Uintra search is set to 0.4.0 but there are no other packages for it.
Please advise.

**Comment by denprodan** [comment]
Hi Chris
You dont have to update any Nuget packages on solution. When I suggested to downgrade elasticsearch version I meant version of your elasticsearch server which defined in elasticConfiguration section in web.config
So what version of your elasticsearch server? If it's not 5.2.1 please resetup to 5.2.1

**Comment by ChrisAngel447** [comment]
Hi Denis,

To be dead honest I did not know that this was a prerequisite for Unintra.
I will have to go and install it first and then get back to trying it out.

Kind regards and thanks
Chris

**Comment by denprodan** [comment]
Don't forget to change url and port in elasticSearch config section. Don't hesitate to ask anything about elasticsearch installation if needed

**Comment by ChrisAngel447** [comment]
Working like a charm!
![image](https://user-images.githubusercontent.com/9823098/48621025-e1fd8300-e9aa-11e8-8fbb-62af60a493ad.png)

Thank you very much! 

Just for other users:

1. Install latest Java SE Development Kit
2. Add JAVA_HOME as Environment Variable in advanced system Properties.
3. Download Elasticsearch 5.2.1.
4. On Windows install the elasticsearch-service.bat file from extracted zip file above.
5. Start the service.
6. check that it is running in your web browser on http://localhost:9200/.
7. make sure URL in the config file is set to the same URL with the port.
8. log in to Umbraco back office, go to settings, Elastic Search tab and click on Rebuild Elasticsearch Index.
9. refresh Uintra and test.

Denis let me know if I missed anything and if I can leave this here.

Thank you for all the help!

**Comment by denprodan** [comment]
You welcome, Chris

**Comment by Cookzenberg** [comment]
Hi Miguel, did you follow these instructions already:

https://github.com/Uintra/Uintra/issues/3#issuecomment-439379500

?

**Comment by MiguelIPerez** [comment]
Yes and i cant start the elasticsearch service, i am stuck in that

![image](https://user-images.githubusercontent.com/36245944/50354456-9f831500-0519-11e9-9c8c-978f7b193197.png)

**Comment by MiguelIPerez** [comment]
My pc is x64bit based

**Comment by Cookzenberg** [comment]
Can you run it from a command console (not as a service)?

**Comment by Cookzenberg** [comment]
C:\elasticsearch-5.2.1\bin>elasticsearch
[2018-12-21T15:43:58,641][INFO ][o.e.n.Node               ] [] initializing ...
[2018-12-21T15:43:58,919][INFO ][o.e.e.NodeEnvironment    ] [4mGh_Y2] using [1]
data paths, mounts [[(C:)]], net usable_space [413.7gb], net total_space [1tb],
spins? [unknown], types [NTFS]... etc etc

**Comment by MiguelIPerez** [comment]
I use the java sdk 11 and it started propely

**Comment by MiguelIPerez** [comment]
works like a charm!
